### ISSUE TITLE
warning信息

### ISSUE THREAD

**Issue by lanceyliao** [vnpy/vnpy_influxdb#10]
C:\veighna_studio\lib\site-packages\influxdb_client\client\warnings.py:31: MissingPivotFunction: The query doesn't contains the pivot() function.

The result will not be shaped to optimal processing by pandas.DataFrame. Use the pivot() function by:

                from(bucket: "firstrate")
                    |> range(start: 2000-01-01T00:00:00Z, stop: 2023-10-26T22:59:12.241082Z)
                    |> filter(fn: (r) =>
                        r._measurement == "bar_data" and
                        r.interval == "d" and
                        r.vt_symbol == "A6_F23_day.LOCAL" and
                        r._field == "close_price"
                    )
                    |> count()
                    |> yield(name: "count")
             |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")

You can disable this warning by:
    import warnings
    from influxdb_client.client.warnings import MissingPivotFunction

    warnings.simplefilter("ignore", MissingPivotFunction)

For more info see:
    - https://docs.influxdata.com/resources/videos/pivots-in-flux/
    - https://docs.influxdata.com/flux/latest/stdlib/universe/pivot/
    - https://docs.influxdata.com/flux/latest/stdlib/influxdata/influxdb/schema/fieldsascols/

  warnings.warn(message, MissingPivotFunction)
C:\veighna_studio\lib\site-packages\influxdb_client\client\warnings.py:31: MissingPivotFunction: The query doesn't contains the pivot() function.

The result will not be shaped to optimal processing by pandas.DataFrame. Use the pivot() function by:

                from(bucket: "firstrate")
                    |> range(start: 2000-01-01T00:00:00Z, stop: 2023-10-26T22:59:12.494056Z)
                    |> filter(fn: (r) =>
                        r._measurement == "bar_data" and
                        r.interval == "d" and
                        r.vt_symbol == "A6_G23_day.LOCAL" and
                        r._field == "close_price"
                    )
                    |> count()
                    |> yield(name: "count")
             |> pivot(rowKey:["_time"], columnKey: ["_field"], valueColumn: "_value")

You can disable this warning by:
    import warnings
    from influxdb_client.client.warnings import MissingPivotFunction

    warnings.simplefilter("ignore", MissingPivotFunction)

For more info see:
    - https://docs.influxdata.com/resources/videos/pivots-in-flux/
    - https://docs.influxdata.com/flux/latest/stdlib/universe/pivot/
    - https://docs.influxdata.com/flux/latest/stdlib/influxdata/influxdb/schema/fieldsascols/

  warnings.warn(message, MissingPivotFunction)
......................................等等

**Comment by lanceyliao** [comment]
另一个bug，服务端的一些报错：
2023-10-26T15:13:01.686426Z     info    saving field index changes (end)        {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "end", "op_elapsed": "8.284ms"}
2023-10-26T15:13:01.705893Z     info    index opened with 8 partitions  {"log_id": "0l75vL4G000", "service": "storage-engine", "index": "tsi"}
2023-10-26T15:13:01.708498Z     info    loading changes (start) {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "start"}
2023-10-26T15:13:01.710091Z     info    loading changes (end)   {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "end", "op_elapsed": "1.593ms"}
2023-10-26T15:13:01.711128Z     info    Reindexing TSM data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 277}
2023-10-26T15:13:01.712371Z     info    Reindexing WAL data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 277}
2023-10-26T15:13:01.719403Z     info    saving field index changes (start)      {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "start"}
2023-10-26T15:13:01.723397Z     info    saving field index changes (end)        {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "end", "op_elapsed": "3.994ms"}
2023-10-26T15:13:01.754111Z     info    index opened with 8 partitions  {"log_id": "0l75vL4G000", "service": "storage-engine", "index": "tsi"}
2023-10-26T15:13:01.757264Z     info    loading changes (start) {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "start"}
2023-10-26T15:13:01.757375Z     info    loading changes (end)   {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "end", "op_elapsed": "0.112ms"}
2023-10-26T15:13:01.759331Z     info    Reindexing TSM data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 278}
2023-10-26T15:13:01.760393Z     info    Reindexing WAL data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 278}
2023-10-26T15:13:01.769862Z     info    saving field index changes (start)      {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "start"}
2023-10-26T15:13:01.775648Z     info    saving field index changes (end)        {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "end", "op_elapsed": "5.786ms"}
2023-10-26T15:13:01.795983Z     info    index opened with 8 partitions  {"log_id": "0l75vL4G000", "service": "storage-engine", "index": "tsi"}
2023-10-26T15:13:01.799646Z     info    loading changes (start) {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "start"}
2023-10-26T15:13:01.800167Z     info    loading changes (end)   {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "end", "op_elapsed": "0.389ms"}
2023-10-26T15:13:01.802239Z     info    Reindexing TSM data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 286}
2023-10-26T15:13:01.803294Z     info    Reindexing WAL data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 286}
2023-10-26T15:13:01.814892Z     info    saving field index changes (start)      {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "start"}
2023-10-26T15:13:01.823045Z     info    saving field index changes (end)        {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "end", "op_elapsed": "8.153ms"}
2023-10-26T15:13:01.837687Z     info    index opened with 8 partitions  {"log_id": "0l75vL4G000", "service": "storage-engine", "index": "tsi"}
2023-10-26T15:13:01.840829Z     info    loading changes (start) {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "start"}
2023-10-26T15:13:01.841995Z     info    loading changes (end)   {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "end", "op_elapsed": "1.166ms"}
2023-10-26T15:13:01.842885Z     info    Reindexing TSM data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 288}
2023-10-26T15:13:01.843969Z     info    Reindexing WAL data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 288}
2023-10-26T15:13:01.847721Z     info    saving field index changes (start)      {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "start"}
2023-10-26T15:13:01.849766Z     info    saving field index changes (end)        {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "end", "op_elapsed": "2.045ms"}
2023-10-26T15:13:11.843286Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:13:21.732315Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:13:32.371215Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:13:35.867867Z     info    index opened with 8 partitions  {"log_id": "0l75vL4G000", "service": "storage-engine", "index": "tsi"}
2023-10-26T15:13:35.871508Z     info    loading changes (start) {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "start"}
2023-10-26T15:13:35.871508Z     info    loading changes (end)   {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "end", "op_elapsed": "0.000ms"}
2023-10-26T15:13:35.873582Z     info    Reindexing TSM data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 291}
2023-10-26T15:13:35.874605Z     info    Reindexing WAL data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 291}
2023-10-26T15:13:35.938725Z     info    saving field index changes (start)      {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "start"}
2023-10-26T15:13:36.316097Z     info    saving field index changes (end)        {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "end", "op_elapsed": "377.373ms"}
2023-10-26T15:13:36.784551Z     info    index opened with 8 partitions  {"log_id": "0l75vL4G000", "service": "storage-engine", "index": "tsi"}
2023-10-26T15:13:36.789155Z     info    loading changes (start) {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "start"}
2023-10-26T15:13:36.789353Z     info    loading changes (end)   {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "end", "op_elapsed": "0.198ms"}
2023-10-26T15:13:36.790848Z     info    Reindexing TSM data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 292}
2023-10-26T15:13:36.792127Z     info    Reindexing WAL data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 292}
2023-10-26T15:13:36.804231Z     info    saving field index changes (start)      {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "start"}
2023-10-26T15:13:36.807580Z     info    saving field index changes (end)        {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "end", "op_elapsed": "3.349ms"}
2023-10-26T15:13:36.830565Z     info    index opened with 8 partitions  {"log_id": "0l75vL4G000", "service": "storage-engine", "index": "tsi"}
2023-10-26T15:13:36.835285Z     info    loading changes (start) {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "start"}
2023-10-26T15:13:36.836795Z     info    loading changes (end)   {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "end", "op_elapsed": "1.509ms"}
2023-10-26T15:13:36.837654Z     info    Reindexing TSM data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 290}
2023-10-26T15:13:36.839511Z     info    Reindexing WAL data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 290}
2023-10-26T15:13:36.844457Z     info    saving field index changes (start)      {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "start"}
2023-10-26T15:13:36.845892Z     info    saving field index changes (end)        {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "end", "op_elapsed": "1.435ms"}
2023-10-26T15:13:41.815586Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:13:51.615343Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:14:01.740537Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:14:11.978053Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:14:21.487826Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:14:31.761914Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:14:37.775078Z     info    index opened with 8 partitions  {"log_id": "0l75vL4G000", "service": "storage-engine", "index": "tsi"}
2023-10-26T15:14:37.791676Z     info    loading changes (start) {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "start"}
2023-10-26T15:14:37.792795Z     info    loading changes (end)   {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "field indices", "op_event": "end", "op_elapsed": "1.118ms"}
2023-10-26T15:14:37.793835Z     info    Reindexing TSM data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 293}
2023-10-26T15:14:37.794867Z     info    Reindexing WAL data     {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "db_shard_id": 293}
2023-10-26T15:14:37.799011Z     info    saving field index changes (start)      {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "start"}
2023-10-26T15:14:37.800059Z     info    saving field index changes (end)        {"log_id": "0l75vL4G000", "service": "storage-engine", "engine": "tsm1", "op_name": "MeasurementFieldSet", "op_event": "end", "op_elapsed": "1.048ms"}
2023-10-26T15:14:37.800615Z     info    Write failed    {"log_id": "0l75vL4G000", "service": "storage-engine", "service": "write", "shard": 293, "error": "engine: context canceled"}
2023-10-26T15:14:41.588595Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:14:51.552935Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:15:01.429829Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:15:11.417537Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:15:21.435021Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:15:31.451345Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:15:41.434060Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}
2023-10-26T15:15:51.448156Z     error   Unable to write gathered points {"log_id": "0l75vL4G000", "service": "scraper", "scraper-name": "new target", "error": "database not found: 179947ad4b3e6c35"}

**Comment by lance52587** [comment]
日线保存有bug。背景中能读出的是分钟线。日线数据量全是1，且报错。
![image](https://github.com/vnpy/vnpy_influxdb/assets/45159389/4aeb9859-a357-453c-a872-73dc1df27451)
Traceback (most recent call last):
  File "C:\veighna_studio\lib\site-packages\vnpy_datamanager\ui\widget.py", line 302, in show_data
    bars: List[BarData] = self.engine.load_bar_data(
  File "C:\veighna_studio\lib\site-packages\vnpy_datamanager\engine.py", line 158, in load_bar_data
    bars: List[BarData] = self.database.load_bar_data(
  File "C:\veighna_studio\lib\site-packages\vnpy_influxdb\influxdb_database.py", line 285, in load_bar_data
    df: pd.DataFrame = pd.read_csv(result)[3:]
  File "C:\veighna_studio\lib\site-packages\pandas\util\_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "C:\veighna_studio\lib\site-packages\pandas\util\_decorators.py", line 317, in wrapper
    return func(*args, **kwargs)
  File "C:\veighna_studio\lib\site-packages\pandas\io\parsers\readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "C:\veighna_studio\lib\site-packages\pandas\io\parsers\readers.py", line 605, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "C:\veighna_studio\lib\site-packages\pandas\io\parsers\readers.py", line 1442, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "C:\veighna_studio\lib\site-packages\pandas\io\parsers\readers.py", line 1747, in _make_engine
    return mapping[engine](f, **self.options)
  File "C:\veighna_studio\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py", line 92, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas\_libs\parsers.pyx", line 554, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

**Comment by lanceyliao** [comment]
服务器入库数据时是将overview表存在本地的，其他机器如何访问？

**Comment by lanceyliao** [comment]
https://blog.csdn.net/qq_37967783/article/details/105490287
日线存储时观察到有一段时间标的的日线都只有1个数据，不知道有没有考虑这个问题。

**Comment by vnpy** [comment]
1. 已经过滤warnings
2. 服务端报错是找不到数据库，但没有更多细节，这块请提供下完整复现方法
3. 可以调整overview文件的存放目录来实现（比如局域网都可以访问的共享网盘）
4. 这块欢迎发修复PR
